server: 
  port: 7001
 
eureka:
  #此处设置会改变eureka控制台的显示
  datacenter: cloud
  #此处设置会改变eureka控制台的显示
  environment: prod
  dashboard:
    #控制台路径
    path: /dashboard
    #是否启用控制台，如果是false就关闭控制台，控制台页面打不开。默认是true
    enabled: true
  instance:
#    hostname: localhost
    hostname: eureka7001.com #eureka服务端的实例名称
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url: 
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       # 单机 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      
 

 